### PR TITLE
Fix include cwd in EXTRA_CFLAGS

### PR DESCRIPTION
**Pull request by larroy**

### CODE REVIEW

**Comment by valtri** [comment]
What is the distribution? Current EXTRA_CFLAGS works fine on Fedora 16.

**Comment by larroy** [comment]
ubuntu 12

**Comment by giomasce** [comment]
The fix worked also for me, on Debian sid.

**Comment by larroy** [comment]
Somehow the driver is not stable in my setup, anybody having the same problem?

**Comment by giomasce** [comment]
Here it works fine on a 3.2 kernel. On another machine I have a 3.5 kernel and the driver doesn't work: I compiled it with valtri's repository; the modules gets loaded correctly, but the USB DVB-T stick doesn't get recognized. Don't know why.

**Pull request closed without merging**
